<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC8nQOIy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC8nQOIy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC8nQOIy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC8nQOIy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC8nQOIy\App_KernelDevDebugContainer([
    'container.build_hash' => 'C8nQOIy',
    'container.build_id' => '5225ccb0',
    'container.build_time' => 1648424664,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC8nQOIy');
